config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"
  post "create_store", to: "static_pages#create_store"
  get "/stores/:id", to: "static_pages#show", as: "store"
  post "/directions", to: "directions#calculate_route"
  post "/fetch_routes", to: "routes#fetch_routes"
  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  post "/static_pages/:id/bookmarks", to: "static_pages#add_bookmark"

  resources :stores
  resources :bookmarks, only: %i[create destroy]
  get "bookmarks", to: "static_pages#bookmarks", as: "bookmarks_stores"
  resources :routes, only: [ :new, :create, :show ] do
    collection do
      post :reset_session
    end
    member do
      delete :delete_route
    end
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]
  get "search_autocomplete", to: "static_pages#autocomplete"
end

app/controllers/static_pages_Controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top create_store autocomplete]
  protect_from_forgery with: :exception, unless: -> { request.format.json? }

  def top
    @q = Store.ransack(params[:q])
    @stores = @q.result(distinct: true).page(params[:page]).per(3)
    @show_modal = current_user.nil?
  end

  def create_store
    store = Store.find_or_initialize_by(place_id: store_params[:place_id])
    if store.new_record?
      store.assign_attributes(store_params)
      if store.save
        render json: { message: "#{store.name}をStoresテーブルに保存しました" }, status: :created
      else
        Rails.logger.error("保存に失敗しました: #{store.errors.full_messages.join(", ")}")
        render json: { errors: store.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { message: "#{store.name}は既に保存されています" }, status: :ok
    end
  end

  def show
    store = Store.find_by(place_id: params[:id])

    if store
      render json: store, status: :ok
    else
      render json: { error: "店舗が見つかりませんでした" }, status: :not_found
    end
  end

  def bookmarks
    @q = current_user.bookmark_stores.ransack(params[:q])
    @bookmark_stores = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def add_bookmark
    store = Store.find(params[:id])
    current_user.bookmarks.find_or_create_by(store: store)
    render json: { status: "bookmarked", store_id: store.id }
  end

  def autocomplete
    if params[:q].blank?
      render json: []
      return
    end

    @q = Store.ransack(params[:q])
    @stores = @q.result(distinct: true).limit(10)
    render json: @stores.as_json(only: [ :id, :name, :address ])
  end

  private

  def store_params
    params.require(:store).permit(:name, :address, :phone_number, :web_site, :place_id, :latitude, :longitude)
  end
end

app/views/static_pages/_bookmark.html.erb
<%= link_to bookmarks_path(store_id: store.id), id: "bookmark-button-for-store-#{store.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-star"></i>
<% end %>

app/views/static_pages/_bookmark_buttons.html.erb
<div class="ms-auto">
  <% if current_user && current_user.bookmark?(store) %>
    <%= link_to bookmark_path(current_user.bookmarks.find_by(store_id: store.id)), id: "unbookmark-button-for-store-#{store.id}", data: { turbo_method: :delete } do %>
      <i class="bi bi-star-fill"></i>
    <% end %>
  <% elsif current_user %>
    <%= link_to bookmarks_path(store_id: store.id), id: "bookmark-button-for-store-#{store.id}", data: { turbo_method: :post } do %>
      <i class="bi bi-star"></i>
    <% end %>
  <% end %>
</div>

app/views/static_pages/_search.html.erb
<%= stylesheet_link_tag "_search", media: "all" %>
<div class="row justify-content-center">
  <div class="col-lg-10 col-md-12">
    <%= search_form_for q, url: url, method: :get, html: { class: "search-form-wrapper align-items-center" } do |f| %>
      <div class="form-group position-relative" data-controller="autocomplete" data-autocomplete-url-value="<%= search_autocomplete_path %>">
        <div class="search-box">
          <%= f.search_field :name_or_address_cont, id: "name_or_address_cont",
                class: "form-control search-input",
                placeholder: "店名または住所を入力してください",
                data: { action: "input->autocomplete#search", autocomplete_target: "input" } %>
          <button type="submit" class="search-icon-button">
            <i class="fas fa-search"></i>
          </button>
        </div>
        <ul data-autocomplete-target="results" class="autocomplete-results list-group mt-2"></ul>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(store_id: store.id)), id: "unbookmark-button-for-store-#{store.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-star-fill"></i>
<% end %>

app/views/static_pages/bookmarks.html.erb
<div class="container pt-3">
  <%= stylesheet_link_tag "bookmarks", media: "all" %>
  <div class="row">
    <div class="col-lg-10 offset-lg-1 flex-column d-flex justify-content-between align-items-center custom-spacing">
      <h1 class="gradient-title mb-4 mx-auto">スイーツサーチ</h1>
      <%= link_to "トップページに戻る", root_path, class: "btn btn-primary" %>
      <%= link_to "ルートを作成する", new_route_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <%= render "search", q: @q, url: bookmarks_path %>

  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_stores.present? %>
          <% @bookmark_stores.each do |store| %>
            <%= render "stores/store", store: store %>
          <% end %>
        <% else %>
          <p><%= t(".no_result") %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-centent-center">
    <%= paginate @bookmark_stores, theme: "bootstrap-5" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/static_pages/top.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TOP画面</title>
  <%= stylesheet_link_tag "top", media: "all" %>
  <%= stylesheet_link_tag "pagination", media: "all" %>
  <%= stylesheet_link_tag "_startup_modal", media: "all" %>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
  <meta name="csrf-token" content="<%= form_authenticity_token %>">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="top-page">
  <% if @show_modal %>
    <%= render "shared/startup_modal" %>
  <% end %>

  <% if logged_in? %>
    <%= render "shared/header" %>
  <% else %>
    <%= render "shared/before_login_header" %>
  <% end %>
  <div class="col-12">
    <%= render "search", q: @q, url: root_path %>
  </div>
  <div class="main-container">
    <div id="map"></div>
    <div class="store-container">
      <div class="grid">
        <% @stores.each do |store| %>
          <div class="col-md-4 mb-4">
            <div class="card" data-store-id="<%= store.id %>">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="card-title"><%= store.name %></h5>
                  <%= render "bookmark_buttons", { store: store } %>
                </div>
                <hr>
                <p class="card-text">住所: <%= store.address %></p>
                <p class="card-text">電話番号: <%= store.phone_number %></p>

                <% if current_user && current_user.own?(store) %>
                  <div class="ms-auto">
                    <%= link_to edit_store_path(store), id: "button-edit-#{store.id}" do %>
                      <i class="bi bi-pencil-fill"></i>
                    <% end %>
                    <%= link_to store_path(store), id: "button-delete-#{store.id}", data: { turbo_method: :delete, turbo_confirm: t("defaults.delete_confirm") } do %>
                      <i class="bi bi-trash-fill"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <button id="show-all-markers" class="m-btn btn btn-primary mt-3">全て表示</button>
    </div>
  </div>
  <div class="pagination-container">
    <%= paginate @stores, theme: "bootstrap-5" %>
  </div>
  <div class="footer-css">
    <%= render "shared/footer" %>
  </div>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
  <%= javascript_include_tag 'leaflet-map' %>
  <%= javascript_include_tag 'startup_modal' %>
</body>
</html>