config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"
  post "create_store", to: "static_pages#create_store"
  get "/stores/:id", to: "static_pages#show", as: "store"
  post "/directions", to: "directions#calculate_route"
  post "/fetch_routes", to: "routes#fetch_routes"
  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  post "/static_pages/:id/bookmarks", to: "static_pages#add_bookmark"

  resources :stores
  resources :bookmarks, only: %i[create destroy]
  get "bookmarks", to: "static_pages#bookmarks", as: "bookmarks_stores"
  resources :routes, only: [ :new, :create, :show ] do
    collection do
      post :reset_session
    end
    member do
      delete :delete_route
    end
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]
  get "search_autocomplete", to: "static_pages#autocomplete"
end

app/models/store.rb
class Store < ApplicationRecord
  validates :name, :address, :phone_number, :place_id, :latitude, :longitude, presence: true

  belongs_to :user, optional: true
  has_many :bookmarks, dependent: :destroy

  def self.ransackable_associations(auth_object = nil)
    [ "bookmarks", "user" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "name", "address", "phone_number", "latitude", "longitude", "place_id", "web_site" ]
  end
end

app/views/stores/_bookmarks.html.erb
<%= stylesheet_link_tag "_bookmarks", media: "all" %>
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="card-title"><%= bookmark.store.name %></h5>
        <div class="form-check">
          <%= check_box_tag "bookmark_ids[]", bookmark.id, false, class: "form-check-input", id: "bookmark_#{bookmark.id}" %>
          <%= label_tag "bookmark_#{bookmark.id}", "ルート作成したいお店をチェック", class: "form-check-label" %>
        </div>
      </div>
      <hr>
      <p class="card-text">住所: <%= bookmark.store.address %></p>
      <p class="card-text">電話番号: <%= bookmark.store.phone_number %></p>
    </div>
  </div>
</div>

app/views/stores/_store.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="card-title"><%= store.name %></h5>
        <%= render "bookmark_buttons", { store: store } %>
      </div>
      <hr>
      <p class="card-text">住所: <%= store.address %></p>
      <p class="card-text">電話番号: <%= store.phone_number %></p>

      <% if current_user.own?(store) %>
        <div class="ms-auto">
          <%= link_to edit_store_path(store), id: "button-edit-#{store.id}" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
          <%= link_to store_path(store), id: "button-delete-#{store.id}", data: { turbo_method: :delete, turbo_confirm: t("defaults.delete_confirm") } do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>