config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"
  post "create_store", to: "static_pages#create_store"
  get "/stores/:id", to: "static_pages#show", as: "store"
  post "/directions", to: "directions#calculate_route"
  post "/fetch_routes", to: "routes#fetch_routes"
  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  post "/static_pages/:id/bookmarks", to: "static_pages#add_bookmark"

  resources :stores
  resources :bookmarks, only: %i[create destroy]
  get "bookmarks", to: "static_pages#bookmarks", as: "bookmarks_stores"
  resources :routes, only: [ :new, :create, :show ] do
    collection do
      post :reset_session
    end
    member do
      delete :delete_route
    end
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]
  get "search_autocomplete", to: "static_pages#autocomplete"
end

app/views/shared/_before_login_header.html.erb
<header>
  <%= stylesheet_link_tag "_header", media: "all" %>
  <span class="gradient-title">スイーツサーチ</span>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      ☰
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t("header.new_user_create"), new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("header.login"), login_path, class: "nav-link" %>
        </li>
        <li class="explanation-link">
          <a data-turbo="false" href="/explanation">使い方</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= stylesheet_link_tag "_footer", media: "all" %>
  <div class="copyright-container">
    <span>Copyright © 2025. Sweets_sarch</span>
  </div>
  <div class="footer-links">
    <a data-turbo="false" href="/terms">利用規約</a>
    <a data-turbo="false" href="/privacy_policy">プライバシーポリシー</a>
    <a data-turbo="false" href="/contact">お問い合わせ</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag "_header", media: "all" %>
<header class="header">
  <span class="gradient-title">スイーツサーチ</span>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      ☰
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t("header.bookmark_index"), bookmarks_stores_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("header.logout"), logout_path, class: "nav-link", data: { turbo_method: :delete } %>
        </li>
        <div class="explanation-link">
          <a data-turbo="false" href="/explanation">使い方</a>
        </div>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_startup_modal.html.erb
<body>
  <div class="modal fade" id="startupModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">アプリの使い方</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <img src="https://i.gyazo.com/00e81f3d44b51feda5cda4630f5718f0.gif" class="m-explanation-image">
          <div class="startup-modal">
            <div class="card">
              <div class="card-body">
               <p class="card-tex">Map上に現在地周辺のスイーツ店がスイーツの種類ごとにアイコンとして表示されます。（例：洋菓子を出すお店はケーキのアイコンを表示）</p>
              </div>
            </div>
          </div>
          <img src="https://i.gyazo.com/1648afedf5dcc7e07194d3d32ee8961d.gif" class="m-explanation-image">
          <div class="startup-modal">
            <div class="card">
              <div class="card-body">
                <p class="card-text">ブックマークに追加したお店のルートを作成することができます。</p>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-primary button-center" data-bs-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</body>