config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"
  post "create_store", to: "static_pages#create_store"
  get "/stores/:id", to: "static_pages#show", as: "store"
  post "/directions", to: "directions#calculate_route"
  post "/fetch_routes", to: "routes#fetch_routes"
  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  post "/static_pages/:id/bookmarks", to: "static_pages#add_bookmark"

  resources :stores
  resources :bookmarks, only: %i[create destroy]
  get "bookmarks", to: "static_pages#bookmarks", as: "bookmarks_stores"
  resources :routes, only: [ :new, :create, :show ] do
    collection do
      post :reset_session
    end
    member do
      delete :delete_route
    end
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]
  get "search_autocomplete", to: "static_pages#autocomplete"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, notice: "ログインしました"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが無効です"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<%= stylesheet_link_tag "new_sessions", media: "all" %>
<div class="container">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto text-center">
      <h1 class="font-weight-bold">ログイン</h1>
      <%= form_with url: login_path, lacal: true do |f| %>
        <div class="mb-3">
          <%= f.email_field :email, class: "form-control", id: "user_email", placeholder: "メールアドレス" %>
          <div class="error-message"></div>
        </div>
        <div class="mb-3">
          <%= f.password_field :password, class: "form-control", id: "user_password", placeholder: "パスワード（6文字以上半角英数字のみ）" %>
          <div class="error-message"></div>
        </div>
        <%= f.submit t(".login"), class: "text-primary btn btn-primary btn-lg", style: "background-color: #ffeb3b; border-color: #ffeb3b; margin: 30px" %>
      <% end %>
      <div class="text">
        <%= link_to t(".to_register_page"), new_user_path, class: "text-link" %>
      </div>
      <div class="text">
        <%= link_to "パスワードをお忘れの方はこちら", new_password_reset_path, class: "password-reseet" %>
      </div>
      <div class="text">
        <%= link_to "Googleアカウントでログイン", auth_at_provider_path(provider: :google), class: "google-login" %>
      </div>
    </div>
  </div>
</div>
<div class="footer-css">
  <%= render "shared/footer" %>
</div>